// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1XxsFPKvtboXLHYAKhriiFBpOGmzspW4',
    appId: '1:94788957511:android:aec217e2774a251e2fc862',
    messagingSenderId: '94788957511',
    projectId: 'flusample',
    storageBucket: 'flusample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-795qNT9fXnZkwUDQAO93DcbzLW9GYaE',
    appId: '1:94788957511:ios:160692f39c91ee1a2fc862',
    messagingSenderId: '94788957511',
    projectId: 'flusample',
    storageBucket: 'flusample.appspot.com',
    iosClientId: '94788957511-oava9fea7mdq8iq4hhaqi9shi823ljek.apps.googleusercontent.com',
    iosBundleId: 'com.example.flufireSample',
  );
}
